services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: carhub-frontend

    ports:
      - "5173:5173"

    volumes:
      - .:/app
      - node_modules:/app/node_modules

    environment:
      VITE_API_URL: http://localhost:8080/api

volumes:
  node_modules: