services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev

    container_name: carhub-backend

    ports:
      - "8080:8000"

    volumes:
      - .:/var/www

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: carhub
      DB_USERNAME: laravel
      DB_PASSWORD: laravel

    networks:
      - carhub-network

  mysql:
    image: mysql:8.0

    container_name: carhub-mysql

    restart: unless-stopped

    environment:
      MYSQL_DATABASE: carhub
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

    networks:
      - carhub-network


volumes:
  mysql_data:


networks:
  carhub-network:
    driver: bridge